server:
  port: 9000
spring:
  application:
    name: zookeeper-lock
  datasource:
    url: jdbc:mysql://111.229.237.223:3306/lock-test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#zookeeper 配置
#zk:
#  connectAddr: 192.168.91.139:2181,192.168.91.140:2181,192.168.91.141:2181
mapper:
  mappers: com.zhou.zookeeper.core.MyMapper
  not-empty: false
  identity: MYSQL
logging:
  level:
    root: info