server:
  port: 9000
spring:
  application:
    name: zookeeper-lock
  datasource:
    url: jdbc:mysql://111.229.237.223:3306/lock-test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
    cache:
      host: 127.0.0.1
      database: 0
      port: 6379
      expire: 1800
      timeout: 0
  redisson:
    address: redis://127.0.0.1:6379
mapper:
  mappers: com.zhou.core.MyMapper
  not-empty: false
  identity: MYSQL
logging:
  level:
    root: info
#zookeeper分布式锁curator配置
curator:
  connectionTimeoutMs: 5000  # 连接超时时间
  elapsedTimeMs: 5000   #重试间隔时间
  retryCount: 3   #重試次數
  sessionTimeoutMs: 60000  # session超时时间
  connectString: 192.168.91.139:2181,192.168.91.140:2181,192.168.91.140:2181   # zookeeper 地址
